export const GET_SUPERADMINS_PENDING = 'GET_SUPERADMINS_PENDING';
export const GET_SUPERADMINS_SUCCESS = 'GET_SUPERADMINS_SUCCESS';
export const GET_SUPERADMINS_ERROR = 'GET_SUPERADMINS_ERROR';

export const POST_SUPERADMINS_PENDING = 'POST_SUPERADMINS_PENDING';
export const POST_SUPERADMINS_SUCCESS = 'POST_SUPERADMINS_SUCCESS';
export const POST_SUPERADMINS_ERROR = 'POST_SUPERADMINS_ERROR';

export const PUT_SUPERADMINS_PENDING = 'PUT_SUPERADMINS_PENDING';
export const PUT_SUPERADMINS_SUCCESS = 'PUT_SUPERADMINS_SUCCESS';
export const PUT_SUPERADMINS_ERROR = 'PUT_SUPERADMINS_ERROR';

export const DELETE_SUPERADMINS_PENDING = 'DELETE_SUPERADMINS_PENDING';
export const DELETE_SUPERADMINS_SUCCESS = 'DELETE_SUPERADMINS_SUCCESS';
export const DELETE_SUPERADMINS_ERROR = 'DELETE_SUPERADMINS_ERROR';
