export const GET_CLASSES_PENDING = 'GET_CLASSES_PENDING';
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_ERROR = 'GET_CLASSES_ERROR';

export const POST_CLASS_PENDING = 'POST_CLASS_PENDING';
export const POST_CLASS_SUCCESS = 'POST_CLASS_SUCCESS';
export const POST_CLASS_ERROR = 'POST_CLASS_ERROR';

export const DELETE_CLASS_PENDING = 'DELETE_CLASS_PENDING';
export const DELETE_CLASS_SUCCESS = 'DELETE_CLASS_SUCCESS';
export const DELETE_CLASS_ERROR = 'DELETE_CLASS_ERROR';

export const PUT_CLASS_PENDING = 'PUT_CLASS_PENDING';
export const PUT_CLASS_SUCCESS = 'PUT_CLASS_SUCCESS';
export const PUT_CLASS_ERROR = 'PUT_CLASS_ERROR';

export const RESET_STATE = 'RESET_STATE';
