export const SUBSCRIPTIONS_PENDING = 'SUBSCRIPTIONS_PENDING';
export const SELECT_ID = 'SELECT_ID';

export const GET_SUBSCRIPTIONS_SUCCESS = 'GET_SUBSCRIPTIONS_SUCCESS';
export const GET_SUBSCRIPTIONS_ERROR = 'GET_SUBSCRIPTIONS_ERROR';

export const DELETE_SUBSCRIPTIONS_SUCCESS = 'DELETE_SUBSCRIPTIONS_SUCCESS';
export const DELETE_SUBSCRIPTIONS_ERROR = 'DELETE_SUBSCRIPTIONS_ERROR';

export const POST_SUBSCRIPTIONS_SUCCESS = 'POST_SUBSCRIPTIONS_SUCCESS';
export const POST_SUBSCRIPTIONS_ERROR = 'POST_SUBSCRIPTIONS_ERROR';
