export const GET_TRAINERS_PENDING = 'GET_TRAINERS_PENDING';
export const GET_TRAINERS_SUCCESS = 'GET_TRAINERS_SUCCESS';
export const GET_TRAINERS_ERROR = 'GET_TRAINERS_ERROR';
export const DELETE_TRAINERS_PENDING = 'DELETE_TRAINERS_PENDING';
export const DELETE_TRAINERS_SUCCESS = 'DELETE_TRAINERS_SUCCESS';
export const DELETE_TRAINERS_ERROR = 'DELETE_TRAINERS_ERROR';
