export const GET_MEMBERS_PENDING = 'GET_MEMBERS_PENDING';
export const GET_MEMBERS_SUCCESS = 'GET_MEMBERS_SUCCESS';
export const GET_MEMBERS_ERROR = 'GET_MEMBERS_ERROR';

export const GET_MEMBER_BY_ID_PENDING = 'GET_MEMBER_BY_ID_PENDING';
export const GET_MEMBER_BY_ID_SUCCESS = 'GET_MEMBER_BY_ID_SUCCESS';
export const GET_MEMBER_BY_ID_ERROR = 'GET_MEMBER_BY_ID_ERROR';

export const UPDATE_MEMBERS_PENDING = 'UPDATE_MEMBERS_PENDING';
export const UPDATE_MEMBERS_SUCCESS = 'UPDATE_MEMBERS_SUCCESS';
export const UPDATE_MEMBERS_ERROR = 'UPDATE_MEMBERS_ERROR';

export const CREATE_MEMBERS_PENDING = 'CREATE_MEMBERS_PENDING';
export const CREATE_MEMBERS_SUCCESS = 'CREATE_MEMBERS_SUCCESS';
export const CREATE_MEMBERS_ERROR = 'CREATE_MEMBERS_ERROR';

export const DELETE_MEMBERS_PENDING = 'DELETE_MEMBERS_PENDING';
export const DELETE_MEMBERS_SUCCESS = 'DELETE_MEMBERS_SUCCESS';
export const DELETE_MEMBERS_ERROR = 'DELETE_MEMBERS_ERROR';

export const RESET_INITIAL_STATE = 'RESET_INITIAL_STATE';
